industry:
    inputs:
        path-energy-balances: build/data/annual-energy-balances.csv
        path-cat-names: config/energy-balances/energy-balance-category-names.csv
        path-carrier-names: config/energy-balances/energy-balance-carrier-names.csv
    outputs:
    params:
        year-range: [2000, 2018]  # Start and end year for JRC data parsing
        specific-industries: ["Iron and steel", "Chemicals Industry"]
        steel:
            recycled-steel-share: 0.5  # % of recycled scrap steel for H-DRI
    setup:
        main-out-path: data/industry  # Path to use in case output files must be created at the EC level.
